using DustInTheWind.NN.Toolkit.Cli.ConsoleUtils;

namespace DustInTheWind.NN.Toolkit.Cli.UseCases.Help;

public class HelpUseCase : IUseCase
{
    public void Execute()
    {
        XConsole.Create()
            .WriteLine("Usage:")
            .WriteLine()
            .WriteLine("account import [--file <pdf-file-path>]")
            .With(ConsoleColor.DarkGray, null)
            .WriteLine("  Imports the contribution records from an NN contribution statement PDF file.")
            .WriteLine()
            .With(null, null)
            .WriteLine("account clear")
            .With(ConsoleColor.DarkGray, null)
            .WriteLine("  Clears all contribution records from the database.")
            .WriteLine()
            .With(null, null)
            .WriteLine("account export [--format <format-name>]")
            .With(ConsoleColor.DarkGray, null)
            .WriteLine("  Exports the contribution records from the database to a file in the specified format.")
            .With(null, null)
            .WriteLine("account")
            .With(ConsoleColor.DarkGray, null)
            .WriteLine("  Displays the contributions from the current account.")
            .WriteLine()
            .With(null, null)
            .WriteLine("fund import --from <date> --to <date>")
            .With(ConsoleColor.DarkGray, null)
            .WriteLine("  Imports the fund values for the specified date range from NN's website.")
            .WriteLine()
            .With(null, null)
            .WriteLine("fund import --year <year>")
            .With(ConsoleColor.DarkGray, null)
            .WriteLine("  Imports the fund values for the specified year from NN's website.")
            .WriteLine()
            .With(null, null)
            .WriteLine("fund import --file <filePath>")
            .With(ConsoleColor.DarkGray, null)
            .WriteLine("  Imports the fund values from a CSV file. The file must have the same format as the historical fund values CSV file that can be downloaded from NN's website.")
            .WriteLine()
            .With(null, null)
            .WriteLine("fund clear")
            .With(ConsoleColor.DarkGray, null)
            .WriteLine("  Clears all fund values from the database.")
            .WriteLine()
            .With(null, null)
            .WriteLine("fund")
            .With(ConsoleColor.DarkGray, null)
            .WriteLine("  Displays the fund values from the database.")
            .WriteLine()
            .With(null, null)
            .WriteLine("help")
            .With(ConsoleColor.DarkGray, null)
            .WriteLine("  Displays this help message.");
    }
}